baseURL = 'http://royaire.com'
languageCode = 'en-us'
title = 'Royaire Photography'
theme = 'gallery'
copyright = "Â© Royaire Photography"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[params]

[params.socialIcons]
  instagram = "https://instagram.com/royaire_photography"

[params.imageProcessing]
  cover.enabled=true
  content.enabled=false